//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Lab6.rc
//

// SNOWMAN SKIN 1XXX
#define IDB_SNOWMAN_BKG_BMP                 1001
#define IDB_SNOWMAN_SNOWMAN_BMP             1002
#define IDB_SNOWMAN_RESOURCE_GIFT_BMP       1003
#define IDB_SNOWMAN_RESOURCE1_BMP           1004
#define IDB_SNOWMAN_RESOURCE2_BMP           1005
#define IDB_SNOWMAN_RESOURCE3_BMP           1006
#define IDB_SNOWMAN_RESOURCE_LIFE_BMP       1007
#define IDB_SNOWMAN_PANE_BKG_BMP            1008
#define WAVE_SNOWMAN_GAME_MUSIC             1009
#define WAVE_SNOWMAN_MENU_MUSIC             1010

// EVANGELION SKIN 2XXX
#define IDB_EVANGELION_BKG_BMP              2001
#define IDB_EVANGELION_SNOWMAN_BMP          2002
#define IDB_EVANGELION_RESOURCE_GIFT_BMP    2003
#define IDB_EVANGELION_RESOURCE1_BMP        2004
#define IDB_EVANGELION_RESOURCE2_BMP        2005
#define IDB_EVANGELION_RESOURCE3_BMP        2006
#define IDB_EVANGELION_RESOURCE_LIFE_BMP    2007
#define IDB_EVANGELION_PANE_BKG_BMP         2008
#define WAVE_EVANGELION_GAME_MUSIC          2009
#define WAVE_EVANGELION_MENU_MUSIC          2010

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
